// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateWalletReq struct {
	Address string `json:"address"`
	Balance int64  `json:"balance"`
}

type GetWalletReq struct {
	Address string `path:"address"`
}

type TransferReq struct {
	From   string `json:"from"`
	To     string `json:"to"`
	Amount int64  `json:"amount"`
}

type TransferResp struct {
	From WalletResp `json:"from"`
	To   WalletResp `json:"to"`
}

type WalletResp struct {
	Address string `json:"address"`
	Balance int64  `json:"balance"`
}
