// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	wallet "github.com/web3-wallet-org/go-zero-demo/internal/handler/wallet"
	"github.com/web3-wallet-org/go-zero-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/wallets",
				Handler: wallet.CreateWalletHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wallets/:address",
				Handler: wallet.GetWalletHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallets/transfer",
				Handler: wallet.TransferHandler(serverCtx),
			},
		},
	)
}
